name: insergemobileapplication
description: Aplicativo movil para la empresa Inserge

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1
  firebase_core:
  firebase_auth:
  firebase_storage:
  camera: ^0.10.0+3
  image_picker: ^0.8.6
  cloud_firestore:
  restart_app: 
  http: ^0.13.5
  flutter_unity_widget: ^2022.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/